### ISSUE TITLE
Для шаблона меню mobile-menu сделать автоматический расчёт высоты

### ISSUE THREAD

**Issue by Just-guy** [Just-guy/bitrix#1]

**Comment by Just-guy** [comment]
```php
function OpenMenuNode(oThis)
{
    const item = oThis.parentNode.parentNode;
    const menu = item.closest('.menu-mobile');
    item.classList.toggle('menu-mobile_open');

    let container = oThis.closest('.menu-mobile_open');

    if(container){
        const height = container.querySelector(':scope > .menu-mobile__level-list').clientHeight;
        menu.style.height = height + 'px';
    }else{
        menu.style.height ='auto';
    }
}
```

```css
.menu-mobile{
    position: relative;
    overflow: hidden;
}

.menu-mobile__level-list {
    position: absolute;
    left: -2000px;
    opacity: 0;
    overflow: hidden;
    z-index: -1;
    width: 100%;
    background-color: #ffffff;
    top: 0;
    transition: 0.2s ease-in-out;
    padding: 30px 20px 40px;
}
.menu-mobile__button-back,
.menu-mobile__button-exit {
    display: block;
    cursor: pointer;
    width: 30px;
    height: 30px;
}
.menu-mobile__button-back {
    padding: 5px;
}
.menu-mobile__button-exit {
    padding: 8px;
}
.menu-mobile_open > .menu-mobile__level-list {
    left: 0;
    z-index: 2;
    opacity: 1;
    /*height: 100%;*/
}
/*.menu-mobile {
    position: relative;
    width: 300px;
}*/
.menu-mobile ul {
    list-style-type: none;
}
.menu-mobile__item-text {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 24px;
}
.menu-mobile__next {
    cursor: pointer;
    padding: 0 10px;
    display: flex;
}
.menu-mobile__item-text > a {
    font-weight: 400;
    font-size: 15px;
    line-height: 18px;
    color: #2c2c2c;
}
.menu-mobile__parent-name {
    margin: 45px 0 26px;
    font-weight: 500;
    font-size: 18px;
    line-height: 21px;
    color: #2c2c2c;
}
```
